backend:
  commit_messages:
    create: Create {{collection}} "{{slug}}"
    update: Update {{collection}} "{{slug}}"
    delete: Delete {{collection}} "{{slug}}"
    uploadMedia: Upload "{{path}}"
    deleteMedia: Delete "{{path}}"
    openAuthoring: '{{message}}'
  name: git-gateway
  repo: mabysmal/netushi
  branch: main

media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow
locale: 'es'
site_url: 'https://netushi.com'
logo_url: 'Netushi'

collections:
  - name: "banner-imagenes"
    label: "Imagenes del Banner"
    folder: "content/bannerimgs"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Imagenes"
        name: "imagenes"
        widget: "image"
        required: false
        allow_multiple: true

  - name: "apps-delivery"
    label: "AppsDelivery"
    folder: "content/apps-delivery"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "DidiFood"
        name: "didifood"
        widget: "text"
        required: false
      - label: "UberEats"
        name: "ubereats"
        widget: "text"
        required: false
      - label: "Rappi"
        name: "rappi"
        widget: "text"
        required: false

  - name: "menu"
    label: "Menú"
    folder: "content/menu"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Título del Producto"
        name: "title"
        widget: "text"
        required: true
      - label: "Descripción"
        name: "description"
        widget: "text"
        required: true
      - label: "Precio"
        name: "price"
        widget: "number"
        required: true
        value_type: "float"
        min: 0
        step: 0.01
      - label: "Imagen"
        name: "image"
        widget: "image"
        required: true
        allow_multiple: false
        media_library:
          config:
            multiple: false
      - label: "Categoría"
        name: "category"
        widget: "select"
        required: true
        options:
          - { label: "Promociones", value: "promociones" }
          - { label: "Aperitivos", value: "aperitivos" }
          - { label: "Rollos Fríos", value: "rollos-frios" }
          - { label: "Rollos Fríos Especiales", value: "rollos-frios-especiales" }
          - { label: "Rollos Calientes", value: "rollos-calientes" }
          - { label: "Rollos Calientes Especiales", value: "rollos-calientes-especiales" }
          - { label: "Complementos", value: "complementos" }
          - { label: "Bebidas", value: "bebidas" }
      - label: "Orden de Visualización (0 = primer producto enlistado, 1= segundo producto enlistado, etc.)"
        name: "order"
        widget: "number"
        required: true
        value_type: "int"
        min: 0
        step: 1
        default: 0


        

  # - name: "config"
  #   label: "Config"
  #   delete: false
  #   editor:
  #     preview: false
  #   files:
  #     - name: "general"
  #       label: "Site Config"
  #       file: "config.json"
  #       description: "General site settings"
  #       fields:
  #         - label: "URL"
  #           name: "base_url"
  #           widget: "string"
  #           hint: "Do not enter the trailing slash of the URL"
  #         - label: "Site title"
  #           name: "site_title"
  #           widget: "string" 
  #         - label: "Site description"
  #           name: "site_description"
  #           widget: "string"
  #         - label: "Site keywords"
  #           name: "site_keywords"
  #           widget: "list"
  #           summary: "{{fields.keyword.keyword}}"
  #           field:
  #             label: Keyword
  #             name: keyword
  #             widget: "string"
  #         - label: "Twitter account"
  #           name: "twitter_account"
  #           widget: "string"
  #         - label: "GitHub account"
  #           name: "github_account"
  #           widget: "string"

  # - name: "meta"
  #   label: "Meta"
  #   delete: false
  #   editor:
  #     preview: false
  #   files:
  #     - name: "authors"
  #       label: "Authors"
  #       file: "meta/authors.yml"
  #       description: "Author descriptions"
  #       fields:
  #         - name: authors
  #           label: Authors
  #           label_singular: "Author"
  #           widget: list
  #           fields:
  #             - label: "Slug"
  #               name: "slug"
  #               widget: "string"
  #               hint: "The part of a URL identifies the author"
  #             - label: "Name"
  #               name: "name"
  #               widget: "string"
  #               hint: "First and Last"
  #             - label: "Introduction"
  #               name: "introduction"
  #               widget: "text"
  #     - name: "tags"
  #       label: "Tags"
  #       file: "meta/tags.yml"
  #       description: "List of tags"
  #       fields:
  #         - name: tags
  #           label: Tags
  #           label_singular: "Tag"
  #           widget: list
  #           fields:
  #             - label: "Slug"
  #               name: "slug"
  #               widget: "string"
  #               hint: "The part of a URL identifies the tag"
  #             - label: "Display Name"
  #               name: "name"
  #               widget: "string"
  #               hint: "Tag name for displaying on the site"
              

