backend:
  commit_messages:
    create: Create {{collection}} "{{slug}}"
    update: Update {{collection}} "{{slug}}"
    delete: Delete {{collection}} "{{slug}}"
    uploadMedia: Upload "{{path}}"
    deleteMedia: Delete "{{path}}"
    openAuthoring: '{{message}}'
  name: git-gateway
  repo: mabysmal/netushi
  branch: main

media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow
locale: 'es'
site_url: 'https://netushi.com'
logo_url: 'Netushi'

collections:
  - name: "banner-imagenes"
    label: "Imagenes del Banner"
    folder: "content/bannerimgs"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Titulo"
        name: "titulo"
        widget: "text"
        required: true
      - label: "Imagen"
        name: "imagenes"
        widget: "image"
        required: true
        allow_multiple: false
      - label: "Orden"
        name: "order"
        widget: "number"
        required: true
        value_type: "int"
        min: 0
        default: 0

  - name: "apps-delivery"
    label: "AppsDelivery"
    folder: "content/apps-delivery"
    create: false
    slug: "{{slug}}"
    fields:
      - label: "DidiFood"
        name: "didifood"
        widget: "object"
        fields:
          - {label: "Link", name: "link", widget: "string", required: false}
          - {label: "Activo", name: "active", widget: "boolean", default: true}
      - label: "UberEats"
        name: "ubereats"
        widget: "object"
        fields:
          - {label: "Link", name: "link", widget: "string", required: false}
          - {label: "Activo", name: "active", widget: "boolean", default: true}
      - label: "Rappi"
        name: "rappi"
        widget: "object"
        fields:
          - {label: "Link", name: "link", widget: "string", required: false}
          - {label: "Activo", name: "active", widget: "boolean", default: true}

  - name: "menu"
    label: "Menú"
    folder: "content/menu"
    create: true
    slug: "{{slug}}"
    preview_path: "menu/{{slug}}"
    fields:
      - label: "Título del Producto"
        name: "title"
        widget: "text"
        required: true
      - label: "Descripción"
        name: "description"
        widget: "text"
        required: true
      - label: "Precio"
        name: "price"
        widget: "number"
        required: true
        value_type: "float"
        min: 0
        step: 0.01
      - label: "Imagen"
        name: "image"
        widget: "image"
        required: true
        allow_multiple: false
        media_library:
          config:
            multiple: false
      - label: "Categoría"
        name: "category"
        widget: "select"
        required: true
        options:
          - { label: "Promociones", value: "promociones" }
          - { label: "Entradas", value: "entradas" }
          - { label: "Rollos Fríos", value: "rollos-frios" }
          - { label: "Rollos Calientes", value: "rollos-calientes" }
          - { label: "Complementos", value: "complementos" }
          - { label: "Extras", value: "extras" }
          - { label: "Bebidas", value: "bebidas" }
      - label: "Orden de Visualización (0 = primer producto enlistado, 1= segundo producto enlistado, etc.)"
        name: "order"
        widget: "number"
        required: true
        value_type: "int"
        min: 0
        step: 1
        default: 0
      # - label: "Etiquetas"
      #   name: "tags"
      #   widget: "select"
      #   multiple: true
      #   required: false
      #   options:
      #     - { label: "Picante", value: "spicy" }
      #     - { label: "Vegetariano", value: "vegetarian" }
      #     - { label: "Sin Gluten", value: "gluten-free" }

  # - name: "business-hours"
  #   label: "Horarios de Atención"
  #   folder: "content/business-hours"
  #   create: false
  #   slug: "horarios"
  #   fields:     
  #     - label: "Lunes"
  #       name: "monday"
  #       widget: "object"
  #       fields:
  #         - {label: "Abierto", name: "isOpen", widget: "boolean", default: false}
  #         - {label: "Hora de Apertura", name: "openTime", widget: "string", required: false}
  #         - {label: "Hora de Cierre", name: "closeTime", widget: "string", required: false}
  #     - label: "Martes"
  #       name: "tuesday"
  #       widget: "object"
  #       fields:
  #         - {label: "Abierto", name: "isOpen", widget: "boolean", default: false}
  #         - {label: "Hora de Apertura", name: "openTime", widget: "string", required: false}
  #         - {label: "Hora de Cierre", name: "closeTime", widget: "string", required: false}
  #     - label: "Miércoles"
  #       name: "wednesday"
  #       widget: "object"
  #       fields:
  #         - {label: "Abierto", name: "isOpen", widget: "boolean", default: false}
  #         - {label: "Hora de Apertura", name: "openTime", widget: "string", required: false}
  #         - {label: "Hora de Cierre", name: "closeTime", widget: "string", required: false}
  #     - label: "Jueves"
  #       name: "thursday"
  #       widget: "object"
  #       fields:
  #         - {label: "Abierto", name: "isOpen", widget: "boolean", default: false}
  #         - {label: "Hora de Apertura", name: "openTime", widget: "string", required: false}
  #         - {label: "Hora de Cierre", name: "closeTime", widget: "string", required: false}
  #     - label: "Viernes"
  #       name: "friday"
  #       widget: "object"
  #       fields:
  #         - {label: "Abierto", name: "isOpen", widget: "boolean", default: false}
  #         - {label: "Hora de Apertura", name: "openTime", widget: "string", required: false}
  #         - {label: "Hora de Cierre", name: "closeTime", widget: "string", required: false}
  #     - label: "Sábado"
  #       name: "saturday"
  #       widget: "object"
  #       fields:
  #         - {label: "Abierto", name: "isOpen", widget: "boolean", default: false}
  #         - {label: "Hora de Apertura", name: "openTime", widget: "string", required: false}
  #         - {label: "Hora de Cierre", name: "closeTime", widget: "string", required: false}
  #     - label: "Domingo"
  #       name: "sunday"
  #       widget: "object"
  #       fields:
  #         - {label: "Abierto", name: "isOpen", widget: "boolean", default: false}
  #         - {label: "Hora de Apertura", name: "openTime", widget: "string", required: false}
  #         - {label: "Hora de Cierre", name: "closeTime", widget: "string", required: false}
        

  # - name: "config"
  #   label: "Config"
  #   delete: false
  #   editor:
  #     preview: false
  #   files:
  #     - name: "general"
  #       label: "Site Config"
  #       file: "config.json"
  #       description: "General site settings"
  #       fields:
  #         - label: "URL"
  #           name: "base_url"
  #           widget: "string"
  #           hint: "Do not enter the trailing slash of the URL"
  #         - label: "Site title"
  #           name: "site_title"
  #           widget: "string" 
  #         - label: "Site description"
  #           name: "site_description"
  #           widget: "string"
  #         - label: "Site keywords"
  #           name: "site_keywords"
  #           widget: "list"
  #           summary: "{{fields.keyword.keyword}}"
  #           field:
  #             label: Keyword
  #             name: keyword
  #             widget: "string"
  #         - label: "Twitter account"
  #           name: "twitter_account"
  #           widget: "string"
  #         - label: "GitHub account"
  #           name: "github_account"
  #           widget: "string"

  # - name: "meta"
  #   label: "Meta"
  #   delete: false
  #   editor:
  #     preview: false
  #   files:
  #     - name: "authors"
  #       label: "Authors"
  #       file: "meta/authors.yml"
  #       description: "Author descriptions"
  #       fields:
  #         - name: authors
  #           label: Authors
  #           label_singular: "Author"
  #           widget: list
  #           fields:
  #             - label: "Slug"
  #               name: "slug"
  #               widget: "string"
  #               hint: "The part of a URL identifies the author"
  #             - label: "Name"
  #               name: "name"
  #               widget: "string"
  #               hint: "First and Last"
  #             - label: "Introduction"
  #               name: "introduction"
  #               widget: "text"
  #     - name: "tags"
  #       label: "Tags"
  #       file: "meta/tags.yml"
  #       description: "List of tags"
  #       fields:
  #         - name: tags
  #           label: Tags
  #           label_singular: "Tag"
  #           widget: list
  #           fields:
  #             - label: "Slug"
  #               name: "slug"
  #               widget: "string"
  #               hint: "The part of a URL identifies the tag"
  #             - label: "Display Name"
  #               name: "name"
  #               widget: "string"
  #               hint: "Tag name for displaying on the site"
              

